/**
 * Interpreter-specific Five-Element (五行) relationship math and prose
 * helpers. The underlying stem/branch lexicon (天干/地支 pinyin, element,
 * yin/yang, zodiac) and the 生/克 (generates/controls) tables are NOT
 * duplicated here — they're imported straight from the engine's own
 * `@/lib/bazi/constants`, which is the single source of truth for those
 * closed, unambiguous correspondences. What stays local is genuinely
 * interpreter-specific: English display labels, Ten-God-flavored relation
 * naming (output/wealth/resource/authority), the ganzhi-parsing helper
 * shaped for this module's callers, and the deterministic seeding/pick
 * helpers the mock interpreter uses for prose variation.
 */
import {
  BRANCHES,
  CONTROLS,
  ELEMENT_ORDER,
  GENERATES,
  elementThatControls,
  elementThatGenerates,
  STEMS,
} from "@/lib/bazi/constants";
import type { YinYang } from "@/lib/bazi/constants";
import type { Element } from "@/lib/bazi";

export const ELEMENTS: Element[] = ELEMENT_ORDER;

export const ELEMENT_LABEL: Record<Element, string> = {
  wood: "Wood",
  fire: "Fire",
  earth: "Earth",
  metal: "Metal",
  water: "Water",
};

export type ElementRelation =
  | "same"
  | "generates" // a generates b
  | "generated-by" // a is generated by b
  | "controls" // a controls b
  | "controlled-by"; // a is controlled by b

export function elementRelation(a: Element, b: Element): ElementRelation {
  if (a === b) return "same";
  if (GENERATES[a] === b) return "generates";
  if (GENERATES[b] === a) return "generated-by";
  if (CONTROLS[a] === b) return "controls";
  return "controlled-by";
}

/** The element the day master generates (its "output/expression", 食神/伤官). */
export function outputElement(dayMaster: Element): Element {
  return GENERATES[dayMaster];
}

/** The element the day master controls (its "wealth", 财). */
export function wealthElement(dayMaster: Element): Element {
  return CONTROLS[dayMaster];
}

/** The element that generates the day master (its "resource/support", 印). */
export function resourceElement(dayMaster: Element): Element {
  return elementThatGenerates(dayMaster);
}

/** The element that controls the day master (its "authority/pressure", 官/杀). */
export function authorityElement(dayMaster: Element): Element {
  return elementThatControls(dayMaster);
}

/** Split a two-character ganzhi string (e.g. "甲子") into stem + branch info, using the engine's own stem/branch tables. Returns null if malformed. */
export function parseGanZhi(ganZhi: string): {
  stem: string;
  stemPinyin: string;
  stemElement: Element;
  stemYinYang: YinYang;
  branch: string;
  branchPinyin: string;
  branchAnimal: string;
  branchElement: Element;
} | null {
  const chars = Array.from(ganZhi.trim());
  if (chars.length < 2) return null;
  const [stem, branch] = chars;
  const s = STEMS[stem];
  const b = BRANCHES[branch];
  if (!s || !b) return null;
  return {
    stem,
    stemPinyin: s.pinyin,
    stemElement: s.element,
    stemYinYang: s.yinYang,
    branch,
    branchPinyin: b.pinyin,
    branchAnimal: b.zodiac,
    branchElement: b.element,
  };
}

/** Deterministic, seeded pick — no Math.random(). Same seed + salt always picks the same index. */
export function seededPick<T>(seed: number, salt: number, options: readonly T[]): T {
  const index = Math.abs(seed + salt * 2654435761) % options.length;
  return options[index];
}

/** Deterministic 32-bit-ish string hash (FNV-1a variant) — no Date.now()/Math.random(). */
export function hashString(input: string): number {
  let hash = 2166136261;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash);
}

/** Element with the highest count in an element tally (ties broken by canonical element order). */
export function dominantElement(elements: Record<Element, number>): Element {
  return ELEMENTS.reduce((best, el) => (elements[el] > elements[best] ? el : best), ELEMENTS[0]);
}

/** Element with the lowest count in an element tally (ties broken by canonical element order). */
export function scarceElement(elements: Record<Element, number>): Element {
  return ELEMENTS.reduce((worst, el) => (elements[el] < elements[worst] ? el : worst), ELEMENTS[0]);
}
