/**
 * Shared Five-Element (五行) lexicon and relationship math used by the mock
 * interpreter (to derive real, chart-grounded prose without an LLM) and by
 * prompt-building (to gloss jargon with pinyin + plain English). This is
 * intentionally small and read-only — it mirrors well-known, unambiguous
 * BaZi correspondences, not engine logic.
 */
import type { Element, YinYang } from "./chart-types";

export const ELEMENTS: Element[] = ["wood", "fire", "earth", "metal", "water"];

export const ELEMENT_LABEL: Record<Element, string> = {
  wood: "Wood",
  fire: "Fire",
  earth: "Earth",
  metal: "Metal",
  water: "Water",
};

/** The ten heavenly stems (天干), in order, with element + polarity + pinyin. */
export const HEAVENLY_STEMS: Record<string, { element: Element; yinYang: YinYang; pinyin: string }> = {
  "甲": { element: "wood", yinYang: "yang", pinyin: "jiǎ" },
  "乙": { element: "wood", yinYang: "yin", pinyin: "yǐ" },
  "丙": { element: "fire", yinYang: "yang", pinyin: "bǐng" },
  "丁": { element: "fire", yinYang: "yin", pinyin: "dīng" },
  "戊": { element: "earth", yinYang: "yang", pinyin: "wù" },
  "己": { element: "earth", yinYang: "yin", pinyin: "jǐ" },
  "庚": { element: "metal", yinYang: "yang", pinyin: "gēng" },
  "辛": { element: "metal", yinYang: "yin", pinyin: "xīn" },
  "壬": { element: "water", yinYang: "yang", pinyin: "rén" },
  "癸": { element: "water", yinYang: "yin", pinyin: "guǐ" },
};

/** The twelve earthly branches (地支), with zodiac animal + pinyin. */
export const EARTHLY_BRANCHES: Record<string, { animal: string; pinyin: string; element: Element }> = {
  "子": { animal: "Rat", pinyin: "zǐ", element: "water" },
  "丑": { animal: "Ox", pinyin: "chǒu", element: "earth" },
  "寅": { animal: "Tiger", pinyin: "yín", element: "wood" },
  "卯": { animal: "Rabbit", pinyin: "mǎo", element: "wood" },
  "辰": { animal: "Dragon", pinyin: "chén", element: "earth" },
  "巳": { animal: "Snake", pinyin: "sì", element: "fire" },
  "午": { animal: "Horse", pinyin: "wǔ", element: "fire" },
  "未": { animal: "Goat", pinyin: "wèi", element: "earth" },
  "申": { animal: "Monkey", pinyin: "shēn", element: "metal" },
  "酉": { animal: "Rooster", pinyin: "yǒu", element: "metal" },
  "戌": { animal: "Dog", pinyin: "xū", element: "earth" },
  "亥": { animal: "Pig", pinyin: "hài", element: "water" },
};

/** wood -> fire -> earth -> metal -> water -> wood (生, "generates/feeds"). */
const GENERATES: Record<Element, Element> = {
  wood: "fire",
  fire: "earth",
  earth: "metal",
  metal: "water",
  water: "wood",
};

/** wood -> earth -> water -> fire -> metal -> wood (克, "controls/channels"). */
const CONTROLS: Record<Element, Element> = {
  wood: "earth",
  earth: "water",
  water: "fire",
  fire: "metal",
  metal: "wood",
};

function invert<T extends string>(map: Record<T, T>): Record<T, T> {
  const out = {} as Record<T, T>;
  for (const k of Object.keys(map) as T[]) out[map[k]] = k;
  return out;
}

const GENERATED_BY = invert(GENERATES);
const CONTROLLED_BY = invert(CONTROLS);

export type ElementRelation =
  | "same"
  | "generates" // a generates b
  | "generated-by" // a is generated by b
  | "controls" // a controls b
  | "controlled-by"; // a is controlled by b

export function elementRelation(a: Element, b: Element): ElementRelation {
  if (a === b) return "same";
  if (GENERATES[a] === b) return "generates";
  if (GENERATED_BY[a] === b) return "generated-by";
  if (CONTROLS[a] === b) return "controls";
  return "controlled-by";
}

/** The element the day master generates (its "output/expression", 食神/伤官). */
export function outputElement(dayMaster: Element): Element {
  return GENERATES[dayMaster];
}

/** The element the day master controls (its "wealth", 财). */
export function wealthElement(dayMaster: Element): Element {
  return CONTROLS[dayMaster];
}

/** The element that generates the day master (its "resource/support", 印). */
export function resourceElement(dayMaster: Element): Element {
  return GENERATED_BY[dayMaster];
}

/** The element that controls the day master (its "authority/pressure", 官/杀). */
export function authorityElement(dayMaster: Element): Element {
  return CONTROLLED_BY[dayMaster];
}

/** Split a two-character ganzhi string (e.g. "甲子") into stem + branch info. Returns null if malformed. */
export function parseGanZhi(ganZhi: string): {
  stem: string;
  stemPinyin: string;
  stemElement: Element;
  stemYinYang: YinYang;
  branch: string;
  branchPinyin: string;
  branchAnimal: string;
  branchElement: Element;
} | null {
  const chars = Array.from(ganZhi.trim());
  if (chars.length < 2) return null;
  const [stem, branch] = chars;
  const stemInfo = HEAVENLY_STEMS[stem];
  const branchInfo = EARTHLY_BRANCHES[branch];
  if (!stemInfo || !branchInfo) return null;
  return {
    stem,
    stemPinyin: stemInfo.pinyin,
    stemElement: stemInfo.element,
    stemYinYang: stemInfo.yinYang,
    branch,
    branchPinyin: branchInfo.pinyin,
    branchAnimal: branchInfo.animal,
    branchElement: branchInfo.element,
  };
}

/** Deterministic, seeded pick — no Math.random(). Same seed + salt always picks the same index. */
export function seededPick<T>(seed: number, salt: number, options: readonly T[]): T {
  const index = Math.abs(seed + salt * 2654435761) % options.length;
  return options[index];
}

/** Deterministic 32-bit-ish string hash (FNV-1a variant) — no Date.now()/Math.random(). */
export function hashString(input: string): number {
  let hash = 2166136261;
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return Math.abs(hash);
}

/** Element with the highest count in an element tally (ties broken by canonical element order). */
export function dominantElement(elements: Record<Element, number>): Element {
  return ELEMENTS.reduce((best, el) => (elements[el] > elements[best] ? el : best), ELEMENTS[0]);
}

/** Element with the lowest count in an element tally (ties broken by canonical element order). */
export function scarceElement(elements: Record<Element, number>): Element {
  return ELEMENTS.reduce((worst, el) => (elements[el] < elements[worst] ? el : worst), ELEMENTS[0]);
}
